version: '3'

services:

  nginx:
    build: ./nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - "web"
    volumes:
      - ./static/:/code/static/
      - ./media/:/code/media/
      - ./certs/:/code/certs/
  # postgres:
  #   container_name:  postgres-db
  #   image:           postgres:11
  #   restart: "always"
  #   ports:
  #     - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
  #   volumes:
  #     - ./pgdb:/var/lib/postgresql/data
  #   env_file: .env
  #   environment:
  #     - LC_ALL=C.UTF-8

  # postgres_stat:
  #   container_name:  postgres-stat-db
  #   image:           postgres:11
  #   restart: "always"
  #   ports:
  #     - 5433:5432 # Bind host port 5432 to PostgreSQL port 5432
  #   volumes:
  #     - ./pgdb_stat:/var/lib/postgresql/data
  #   env_file: .env
  #   environment:
  #     - LC_ALL=C.UTF-8


  # redis:
  #   image: redis:5
  #   restart: "always"
  #   container_name: redis
  #   command: redis-server --requirepass $REDIS_PASSWORD
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redisdb:/var/lib/redis
  #   env_file: .env

  # celery:
  #   container_name: celery
  #   build: .
  #   restart: "always"
  #   command: celery --app=qmeter_feedback.celery:app worker -B --loglevel=DEBUG
  #   env_file: .env
  #   environment:
  #     - LANG=C.UTF-8
  #     - LANG=en_US.UTF-8
  #     - LANGUAGE=en_US:en
  #     - LC_ALL=en_US.UTF-8
  #   volumes:
  #     - .:/code
  #   links:
  #     - redis
  #     - postgres
  #   depends_on:
  #     - "redis"
  #     - "postgres"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
  #   container_name: elasticsearch
  #   restart: "always"
  #   env_file: .env
  #   environment:
  #   - discovery.type=single-node
  #   - xpack.security.enabled=true
  #   volumes:
  #     - ./esdata:/usr/share/elasticsearch/data
  #   ports:
  #    - 9200:9200
  #    - 9300:9300

  # traefik:
  #   image: traefik:1.7.0
  #   container_name: traefik
  #   restart: unless-stopped
  #   ports:
  #     - 80:8000
  #     - 443:443
  #   volumes:
  #     - ./traefik.toml:/traefik.toml
  #     - ./certs/:/certs/
  #     - /var/run/docker.sock:/var/run/docker.sock
  
  web:
    container_name: indisat
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=www.indisat.az
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8051
      - LANG=C.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      - .:/code
      - ./media:/code/media
      - ./static:/code/static
    # links:
    #   - postgres
    # depends_on:
    #   - "postgres"

#volumes:
#  esdata:
#    driver: local

# networks:
#   default:
#     external:
#       name: nginx-proxy
